# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02dd917b746467a93687e276eeaf4429ac450ebc1c942d0ed66915d4c7f4f89d51f1bd1623147cbf483e16ef642fef906ed8eedb74f4458043720ef146f1dba9

test:
  secret_key_base: 48f2e2b0944e9843182b3c10c38a5c6c5b2f317fb954599eaf0fa9b93daf2dc6e081e1d5ad831f38057fa44900f3a8e6775d3f6a3524954070bd1e5f69ecf8b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
